// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "http://localhost:5000/home",
    id: "e120c574-d1f3-450a-8641-f56fdfa99180",
    method: "GET",
    address: "http://localhost:5000/home"
  });

  postman[Request]({
    name: "http://localhost:5000/rss",
    id: "efd8103c-c65a-4583-9a13-aa34485f8eef",
    method: "GET",
    address: "http://localhost:5000/home/getcourses"
  });

  postman[Request]({
    name: "http://localhost:5000/getcourses",
    id: "c66a74e7-6d3d-4b8d-a643-fc8e314b49d4",
    method: "GET",
    address: "http://localhost:5000/home/getcourses",
    data: '{\n\t"coursename": "ML intro"\n}'
  });

  postman[Request]({
    name: "http://localhost:5000/home/addtowishlist",
    id: "ae670ef8-7d3d-4693-ae85-6a721a8a81d2",
    method: "POST",
    address: "http://localhost:5000/home/addtowishlist",
    data: '{\n\t"coursename": "intro to ML"\n}'
  });

  postman[Request]({
    name: "http://localhost:5000/home/getwishlist",
    id: "37cd2125-a6d9-4247-ac98-7abf433c540d",
    method: "GET",
    address: "http://localhost:5000/home/getwishlist"
  });
}
